### ISSUE TITLE
adding http/https in apt mirror

### ISSUE THREAD

**Issue by dsx1123** [camrossi/akb#124]
most of apt mirrors supports http only, propose to change the normalize the URL with below change:
- if mirror doesn't start with http or https, use https by default to keep backward compatibility
- if mirror start with http or https, use the URL as is to update the apt source.list

**Comment by dsx1123** [comment]
@camrossi @ddastoli  please let me know your thought

**Comment by camrossi** [comment]
I am fine with this proposed change.

**Comment by dsx1123** [comment]
fixed in #146
