### ISSUE TITLE
Hide vkaci button from create page for NDFC

### ISSUE THREAD

**Issue by camrossi** [camrossi/akb#197]

**Comment by samiib** [comment]
1. Hide vkaci button from create page for NDFC

> - To hide the vkaci button for NDFC, using JS inside the jinja template isn't possible. What I have done instead is pass the variable fabric_type directly through flask. 
> - The fabric_type variable needed to be passed in the render template function for the create page. 
> - Instead of using JS function to find the query parameter for fabric type, I have now used the template variable which is more consistent with the framework we are using for NKT.

2. Fixed defect when changing from No Vm deploy to Vm deploy
3. Added additional test to selenium.
