### ISSUE TITLE
Support for VMM Based Floating L3OUT

### ISSUE THREAD

**Issue by samiib** [camrossi/akb#231]
### **From Steve Sharman** 
> The current workflow does not support configuring a floating L3out on an APIC controlled VDS. This is a very common deployment, so we should support it.
> 
> Adding a portgroup to an APIC controlled VDS causing an alarm in APIC.

**Comment by camrossi** [comment]
The alarm in APIC is cosmetic only. 
We are trying to strike a trade off between simplicity and feature richness so for now we are not going to implement this. We rather focus on delivering a stable 1.0 version.
