### ISSUE TITLE
K8s VM template

### ISSUE THREAD

**Issue by ddastoli** [camrossi/akb#4]
Currently the tool expects a VM template to be exisitng in the VCenter. This template will be used to clone VMs and install K8s. It would be nice if the app can embed the template image and in the workflow the user can request to create the VM template with the embedded image.

**Comment by camrossi** [comment]
The image is already embedded

**Comment by camrossi** [comment]
Will look at how we can upload the template automatically as a nice to have feature.

**Comment by camrossi** [comment]
Implemented
