### ISSUE TITLE
when you go to /cluster directly, UI breaks

### ISSUE THREAD

**Issue by ddastoli** [camrossi/akb#53]
this is due to the fact vc dict is not created and vc["vm_deploy"] does not exist.

**Comment by ddastoli** [comment]
fixed in branch iss53

**Comment by camrossi** [comment]
I reverted the changes in the code. 
You try to access config but this is not even a global variable nor is declared in the plan/apply 
![image](https://user-images.githubusercontent.com/16535101/155923502-83ef11ac-4908-45b0-90e5-6360d36245dc.png)


Also I do not think we ever supported accessing the /cluster directly. 
What I supported accessing directly was /create. 

That was not working but I fixed it now.
