### ISSUE TITLE
Fix Formatting for submit button

### ISSUE THREAD

**Issue by camrossi** [camrossi/akb#60]
For some reason the formatting is not working very well anymore
![image](https://user-images.githubusercontent.com/16535101/155914057-552f9128-9092-47fd-b302-0c7d13d016bb.png)

Also the pop up/helper instead of showing (i) shows [] on Chrome on Linux

If you need to test you can run the application from BM-01 in the lab @mntxca

**Comment by mntxca** [comment]
Fixed in dev now in PR #92

**Comment by mntxca** [comment]
Fixed in dev now in PR https://github.com/camrossi/akb/pull/92
